feat: send windfarm metrics to edgeHub without metrics-collector
omnect/windfarm-monitoring pull request #37
Opened 2024-10-30 10:27 UTC by JoergZeidler

2024-10-30 12:02 UTC, JanZachmann requested changes

2024-10-30 12:11 UTC, JoergZeidler commented on .cargo/config.toml
> +SOCKET_DIR = { value = "/run/aziot", force = false }
could be removed, was needed only for testing....

2024-10-30 12:18 UTC, JoergZeidler commented on src/metrics_provider.rs
> +    static ref IOTEDGE_DEVICEID: String = std::env::var("IOTEDGE_DEVICEID").unwrap();
these envvars are automatically available in all containers started by the edge runtime

2024-10-30 12:41 UTC, JoergZeidler commented on .cargo/config.toml
> +SOCKET_DIR = { value = "/run/aziot", force = false }
done

2024-10-30 12:41 UTC, JoergZeidler commented on Cargo.toml
done

2024-10-30 12:41 UTC, JoergZeidler commented on README.md
> +This module is designed to **demonstrate windfarm signal values** and provides the following metrics via an D2C(device-to-cloud) message:
done

2024-10-30 12:41 UTC, JoergZeidler commented on README.md
> +The device-to-cloud message will be transmitted to edgeHub module on an **edge device** and must be manual routed to the IotHub with the following deployment route:
done

2024-10-30 12:41 UTC, JoergZeidler commented on src/metrics_provider.rs
> +    static ref IOTEDGE_IOTHUBHOSTNAME: String = std::env::var("IOTEDGE_IOTHUBHOSTNAME").unwrap();
done

2024-10-30 12:42 UTC, JoergZeidler commented on src/metrics_provider.rs
> +    static ref IOTEDGE_MODULEID: String = std::env::var("IOTEDGE_MODULEID").unwrap();
done

2024-10-30 12:42 UTC, JoergZeidler commented on src/metrics_provider.rs
> +        info!("LATITUDE: {} LONGITUDE: {}", latitude, longitude);
done

2024-10-31 08:30 UTC, JanZachmann approved these changes

2024-10-31 08:41 UTC, mlilien commented on src/metrics_provider.rs
> +                            }
Imho a builder for each Value would be more convenient, to prevent copy&paste.

2024-11-06 07:59 UTC, mlilien commented on src/metrics_provider.rs
> +                .set_body(serde_json::to_vec(&metric_list).unwrap())
why unwrap and no error handling resp. error logging?

2024-11-06 08:51 UTC, JoergZeidler commented on src/metrics_provider.rs
> +                .set_body(serde_json::to_vec(&metric_list).unwrap())
because, not sure what could be go wrong with the fix metric_list....

2024-11-06 09:43 UTC, JanZachmann commented on src/metrics_provider.rs
> +                .set_body(serde_json::to_vec(&metric_list).unwrap())
@mlilien @elbbbot @JoergZeidler 
imho lines 134 and 139 should end the program `expect("unrecoverable error blablub")` or log an error. I tend to panic as this might get more attention than a error log.

2024-11-08 09:34 UTC, JanZachmann commented on src/metrics_provider.rs
> +                _ => error!("metrics list could not be converted to vector"),
..comment is valid for both match arms

2024-11-08 09:53 UTC, JoergZeidler commented on src/metrics_provider.rs
> +                _ => error!("metrics list could not be converted to vector"),
done

2024-11-08 10:50 UTC, JanZachmann approved these changes

2024-11-08 11:42 UTC, merged